- hs_err_pid24052.log
- hs_err_pid7106.log
- hs_err_pid7292.log
- hs_err_pid7348.log
- hs_err_pid7850.log
- hs_err_pid7916.log
- pom.xml
- src/main/java/com/elle/analyster/Analyster.form
- src/main/java/com/elle/analyster/Analyster.java
- src/main/java/com/elle/analyster/Application.java
- src/main/java/com/elle/analyster/EditDatabaseList.java
- src/main/java/com/elle/analyster/LoadTables.java
- src/main/java/com/elle/analyster/LogWindow.java
- src/main/java/com/elle/analyster/LoginWindow.java
- src/main/java/com/elle/analyster/Tab.java
- src/main/java/com/elle/analyster/configuration/AnalysterConfiguration.java
- src/main/java/com/elle/analyster/service/Connection.java
- src/main/java/com/elle/analyster/service/DeleteRecord.java
- src/main/java/com/elle/analyster/service/TableService.java
Added the log window feature for show all button and removed the check-box order option.
Login Window now displays by itself.
The Log off menu item now displays the Login Window and works properly.
> Analyster_0.6.5c

- build.xml
- src/com/elle/analyster/logic/ITableConstants.java
- src/com/elle/analyster/presentation/AddRecordsWindow.java
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
> add records now works with pupone server

- build.xml
- src/com/elle/analyster/presentation/AnalysterWindow.java
- connection with pupone server is timing out ** FIXED **
> - new archive Analyster_0.8.5a released ** NEW JAR **

- build.xml
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/BatchEditWindow.java
pupone_Analyster database: new Assignments Archived table structure
- column aID (assignments ID) in Assignments_Archived **DONE**
- column dateArchived (todays date) in Assignments_Archived **DONE**
- column ID (primary key auto_increment) in Assignments_Archived **DONE**
TESTING
- pupone_Analyster database
- added records to the assignments table **PASSED**
- archive those test records to the archive table **PASSED**
- then deleted the records from both tables **PASSED**
- new archive Analyster_0.8.6 released ** NEW JAR **
> pupone_Analyster database: new Assignments Archived table structure

- build.xml
- src/com/elle/analyster/database/ModifiedTableData.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
- Analyster had an out of bounds exception for modified data **now fixed**
- out of bounds exception for modified data ** FIXED**
- The modified data was throwing an out of bounds exception because the array size was not accomodating the new records added
- new archive Analyster_0.8.7 released ** NEW JAR **
> **New Jar 0.8.7** (- Analyster had an out of bounds exception for modified data **now fixed**)

- build.xml
- src/com/elle/analyster/presentation/AddRecordsWindow.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
- Analyster had an out of bounds exception for modified data **now fixed**
- out of bounds exception for modified data ** FIXED**
- The modified data was throwing an out of bounds exception because the array was not being reloaded after add records
- new archive Analyster_0.8.7a released ** NEW JAR **
> new jar 0.8.7a, out of bounds exception is now fixed

- build.xml
- src/com/elle/analyster/logic/Tab.java
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/BatchEditWindow.java
- **NEW JAR ** Analyster-0.8.8
- Edit mode label is now green when editing is on
- buttons are enabled according to different states of editing and modified data
> - **NEW JAR ** Analyster-0.8.8 (green edit mode, buttons enabled)

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
Reverts TestingELLE/Analyster#24
> Revert "Search box text change with combo box item selected('symbol', 'analyst')"

- build.xml
- src/com/elle/analyster/presentation/AnalysterWindow.java
this includes the updated build.xml and updated date and version in code for the new jar.
> New Jar 0.9.1 Backup Feature/ SQL Exception handling/ .gitignore update

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
update comboBoxSearch symbol and analyst; 
update add / to path and strip / to  path;
And fixed the problem that 'strip / to path' would not delete slashes which are in the middle of path
> update comboBoxSearch and add or strip / from path;

- build.xml
- src/com/elle/analyster/database/DBConnection.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
new jar 0.9.1b 
session timing out backup feature fix and
parent component added to DBConnection.
> new jar 0.9.1b

- .gitignore
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/BatchEditWindow.form
- src/com/elle/analyster/presentation/BatchEditWindow.java
- src/com/elle/analyster/presentation/LogWindow.java
- src/com/elle/analyster/presentation/LoginWindow.java
update and center the "priority" columns;
update the log file with name format as "Analyster" + username + "log.txt";
> update and center the "priority" columns;

- src/com/elle/analyster/logic/ColumnPopupMenu.java
update dropdown filter, make null value at last and ignore upper lower case.
> update dropdown filter, null value position and ignore case

- build.xml
- src/com/elle/analyster/logic/ColumnPopupMenu.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LogWindow.java
update log file to directory user/library/application support/Analyster, on Mac; to Analyster_logs folder on other os.
> update log file directory

- src/com/elle/analyster/logic/OpenDocumentTool.java
- src/com/elle/analyster/presentation/AddRecordsWindow.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
-- by Carlos on 2016-01-26-- 
Timing out.
- fixed all places I could find where DBConnection was being opened.
> Timing out issue - new jar 1.0.1

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
Rename column author to analyst in Reports;
> Rename column author to analyst in Reports;

- build.xml
- src/com/elle/analyster/logic/FilePathFormat.java
- src/com/elle/analyster/logic/OpenDocumentTool.java
- src/com/elle/analyster/presentation/AddRecordsWindow.java
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- backup feature now working.
- Authorization class implemented.
> new jar 1.0.2

- build.xml
- src/com/elle/analyster/logic/FilePathFormat.java
- src/com/elle/analyster/logic/OpenDocumentTool.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
issue # 156 - open doc tool update
> new jar 1.0.3 - open doc tool update

- build.xml
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LogWindow.java
> fixed log file read error when app is not in C disk

- build.xml
- src/com/elle/analyster/logic/Authorization.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LoginWindow.java
Authorize feature is more efficient. A message notifies the user if they are not authorized. They are not allowed access. This means that they are not on the authorized table in the database.
> New jar 1.0.4 updated the authorization feature

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
update cursor to hand when it is pointing on path or document in reportTable; update comboBox to be editable;
> update cursor and comboBox to be editable

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
update comboBoxSearch category remain same when tab changed; update comboBoxForSearch dropdownlist can directly search when click item from it;
> update functions comboBoxForSearch;

- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LoginWindow.java
update cursor under reports table when select document and path; update design of tools and other categories; update label messages when open document under reports table
> update cursor, design and label message；

- src/com/elle/analyster/presentation/AnalysterWindow.java
fixed dropdown list error which showed same value in priority.
> fixed dropdown list error;

- build.xml
- src/com/elle/analyster/presentation/AnalysterWindow.java
> New Jar 1.1.3 - Connection issue fix for updateTable method

- src/com/elle/analyster/Analyster.java
Hi Professor,
This is the scrollbar thumb bug pull request. Please review it.
Wei
> Analyster Scrollbar thumb invisible bug fixed

- nbproject/project.properties
- src/com/elle/analyster/dao/AccessLevelDAO.java
-Changed the access level table referenced in AccessLevelDAO.java to accessLevels
> Access Level Table Reference

- build.xml
- src/com/elle/analyster/MANIFEST.MF
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LoginWindow.form
- src/com/elle/analyster/presentation/LoginWindow.java
-Increased the size of the JLabels and modified the loading message
-minor adjustments to AnalysterWindow.java layout
> Login Window Layout

- build.xml
- src/com/elle/analyster/dao/BackupDBTableDAO.java
- src/com/elle/analyster/database/DBConnection.java
- src/com/elle/analyster/presentation/AddRecordsWindow.form
- src/com/elle/analyster/presentation/AddRecordsWindow.java
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/LoginWindow.form
- src/com/elle/analyster/presentation/LoginWindow.java
Issues Fixed
1. login messages.
2. Version and server name hard-coded.
3. back-up issue is resolved.
4. Duplicate row issue is resolved.
5. "Clear all filters" issue is fixed.
> Analyster bug fixes - Vesrion 1.6.2 

- build.xml
- src/com/elle/analyster/dao/AssignmentDAO.java
- src/com/elle/analyster/presentation/AnalysterWindow.form
- src/com/elle/analyster/presentation/AnalysterWindow.java
- src/com/elle/analyster/presentation/BatchEditWindow.java
Issues fixed.
1. Batch edit can handle null or blank date fields.
2. Assignments_archived tab is hidden for regular user and viewers.
> BatchEdit with empty date field issue is fixed and Assignments_archived tab is hidden for regular user and viewers.

- build.xml
- src/com/elle/analyster/Analyster.java
- src/com/elle/analyster/MANIFEST.MF
- src/com/elle/analyster/presentation/AnalysterWindow.java
in analysterwindow.java
Changed creation-date and creationDate variables to version-date and versionDate respectively.
in analyster.java
changed creation-date and creationDate variables to version-date and versionDate respectively.
in build.xml
Changed attribute names from creation-date to version-date
Updated version to 1.6.4a and version date to “2018-05-11”
> Made changes to analysterwindow, analysts, and build.xml

- build.xml
Updated to Version 1.6.6
Date - 2018-05-17
> Updated Version and Date
